datasets:
  CONV_DS: "ministere-culture/comparia-conversations"
  REAC_DS: "ministere-culture/comparia-reactions"
  COMPARIA_REQ_DS: "/comparia-requests"
  COMPARIA_HYP_DS: "/comparia-hypotheses"
  MKQA_DS: "apple/mkqa"
  MKQA_REQ_DS: "/mkqa_requests"
  MKQA_HYP_DS: "/mkqa_hypotheses"
username : "dieuant"