QUESTION_WORDS:
  fr:
    - quoi
    - quand
    - comment
    - pourquoi
    - où
    - qui
    - quel
    - quelle 
    - quels
    - quelles
    - lequel
    - combien
  en:
    - what
    - when
    - how
    - why
    - where
    - who
    - which