VERSION:
  CODE_VERSION: "3"
  DATASET: "mkqa"
  DATA_VERSION: "2"
# DATASET: "comparia"
  LANG: "fr"
  REFORMULATION_MODEL: "mistral-medium-latest"
  TESTED_MODELS:
    - "GPT-4o"
    - "Le Chat"
    - "DeepSeek"